---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  labels:
    app: helloworld
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.helloworld: semver:~1.0
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: demo-concourse-flux
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: particule/simplecolorapi:1.0
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
      strategy:
        canary:
          steps:
          - setWeight: 20
          - pause:
              duration: "30s"
          - setWeight: 50
          - pause:
              duration: "30s"
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-concourse-flux
  name: helloworld-svc
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
  type: ClusterIP
